[colors.primary]
background = "#120710"
foreground = "#c3c1c3"

[colors.cursor]
text = "#120710"
cursor = "#c3c1c3"

[colors.vi_mode_cursor]
text = "#120710"
cursor = "#c3c1c3"

[colors.search.matches]
foreground = "#120710"
background = "#c3c1c3"


[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#120710"
red = "#3c055c"
green = "#750c46"
yellow = "#3f3369"
blue = "#b02d18"
magenta = "#93367e"
cyan = "#bc8f17"
white = "#968c94"

[colors.bright]
black = "#6a5667"
red = "#7c439d"
green = "#b24c85"
yellow = "#735fba"
blue = "#c8887e"
magenta = "#c87fb8"
cyan = "#cbb987"
white = "#c3c1c3"
