[colors.primary]
background = "#070710"
foreground = "#c1c1c3"

[colors.cursor]
text = "#070710"
cursor = "#c1c1c3"

[colors.vi_mode_cursor]
text = "#070710"
cursor = "#c1c1c3"

[colors.search.matches]
foreground = "#070710"
background = "#c1c1c3"


[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#070710"
red = "#172462"
green = "#451f3a"
yellow = "#1c3349"
blue = "#3b318a"
magenta = "#792351"
cyan = "#18748d"
white = "#8b8b96"

[colors.bright]
black = "#565669"
red = "#4a5bae"
green = "#9e4486"
yellow = "#4471a0"
blue = "#7f76c4"
magenta = "#bb6091"
cyan = "#66abbd"
white = "#c1c1c3"
