[colors.primary]
background = "#0a0813"
foreground = "#c1c1c4"

[colors.cursor]
text = "#0a0813"
cursor = "#c1c1c4"

[colors.vi_mode_cursor]
text = "#0a0813"
cursor = "#c1c1c4"

[colors.search.matches]
foreground = "#0a0813"
background = "#c1c1c4"


[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0a0813"
red = "#20105e"
green = "#5e1b60"
yellow = "#2e3395"
blue = "#364072"
magenta = "#932869"
cyan = "#5d6da8"
white = "#8e8c96"

[colors.bright]
black = "#5a576b"
red = "#5a47a6"
green = "#ad4baf"
yellow = "#7c7fc6"
blue = "#6877be"
magenta = "#c476a5"
cyan = "#a9b4da"
white = "#c1c1c4"
