[colors.primary]
background = "#12070c"
foreground = "#c3c1c2"

[colors.cursor]
text = "#12070c"
cursor = "#c3c1c2"

[colors.vi_mode_cursor]
text = "#12070c"
cursor = "#c3c1c2"

[colors.search.matches]
foreground = "#12070c"
background = "#c3c1c2"


[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#12070c"
red = "#4f031b"
green = "#69031a"
yellow = "#4e122d"
blue = "#511b33"
magenta = "#9e1818"
cyan = "#a54218"
white = "#968c90"

[colors.bright]
black = "#6a5661"
red = "#923e59"
green = "#a5465c"
yellow = "#9b426a"
blue = "#a3466f"
magenta = "#c27272"
cyan = "#c48e77"
white = "#c3c1c2"
